project:
  type: website
  resources:
    - "assets/**"
  preview:
    port: 4200

execute:
  freeze: auto

website:
  title: "Robert Schauner"
  description: "Data Scientist | Immunologist"
  site-url: https://www.schauner.com

  favicon: assets/icon.png

  twitter-card:
    creator: "@RobertSchauner"

  open-graph: true
  search: false
  google-analytics:
    tracking-id: "G-JT9ZX1TNH2"
    storage: none

  page-footer:
    border: true
    left: |
      <span class="faux-block">{{< fa brands creative-commons title="Creative Commons" >}} 2023 Robert Schauner</span>
      <span class="faux-block"><a href="https://github.com/rschauner/personal_website">{{< fa brands github title="GitHub" >}} Source Code</a></span>
    right: |
      <span class="faux-block"> Designed with {{< fa heart title="love" >}}</span>
      <span class="faux-block"> Built with <a href="https://quarto.org/">Quarto</a></span>

  navbar:
    pinned: true
    background: navbar_bg
    logo: assets/icon.png

    # your sub-pages
    left:
      - text: "Projects"
        href: pages/Projects/index.qmd
      - text: Publications
        href: pages/pubs/index.qmd
      - text: "CV"
        href: pages/cv/index.qmd

    # your social media handles
    right:
      - icon: github
        href: https://github.com/rschauner
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-schauner/
      - text: ORCiD
        href: https://orcid.org/0000-0002-6336-7331
      - icon: envelope
        aria-label: email
        href: "mailto:robert@schauner.com"

format:
  html:
    theme:
     - united
     - styles/styles.scss

    toc: false
