project:
  type: website
  resources:
    - "assets/**"

execute:
  freeze: auto

website:
  title: "Robert Schauner"
  twitter-card: true
  open-graph: true
  search: false

  navbar:
    pinned: true
    background: navbar_bg

    # your sub-pages
    left:
      - text: ""
        href: pages/Projects/index.qmd
      - text: "CV"
        href: pages/cv/index.qmd

    # your social media handles
    right:
      - icon: github
        href: https://github.com/rschauner
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-schauner/
      - text: ORCiD
        href: https://orcid.org/0000-0002-6336-7331
      - icon: envelope
        aria-label: email
        href: "mailto:robert@schauner.com"

format:
  html:
    theme:
     - united
     - styles/styles.scss

    toc: false
