---
layout: page
title: Projects
excerpt: Current and Past Projects
engine: knitr
---


## *O*-GlcNAcylation in AML

A project focused on implicating the Hexoseamine Biosynthetic Pathway and *O*-GlcNAcylation in AML.
We collected a large amount of publicly available data from NCI, St. Jude Children's Research Hospital, and the NIH GEO
to investigate expression of Hexoseamine Biosynthetic Pathway members across AML patient samples and healthy controls.

```{=html}
<a class="btn btn-outline-dark btn-sm", href="https://github.com/rschauner/2024-frontiers-immunology-aml-hbp" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-github" role="img" aria-label="Code on GitHub"></i>
    Code on GitHub
</a>
<a class="btn btn-outline-dark btn-sm", href="https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2024.1327405" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-journal-richtext" role="img" aria-label="Publication"></i>
    Publication
</a>
```

## Pediatric AML Survival Prediction

We wanted to find an approach to predict pediatric FLT3-ITD AML survival.

```{=html}
<a class="btn btn-outline-dark btn-sm", href="https://aacrjournals.org/cancerres/article/82/12_Supplement/4080/702020/Abstract-4080-New-platform-for-novel-biomarker" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-file-earmark-easel" role="img" aria-label="AACR 2022 Abstract"></i>
    AACR 2022 Abstract
</a>
```
----

## Sorting Students into Random Groups

A simple project to make a CLI and GUI to sort students into groups using Rust.
The purpose was:

- I wanted for someone to be able to run this without having R or Python installed,

- Learn a little bit of a compiled language, and

- My fianceé had a use for such a utility.

```{=html}
<a class="btn btn-outline-dark btn-sm", href="https://github.com/rschauner/student-pairs" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-github" role='img' aria-label='Code on GitHub'></i>
    Code on GitHub
</a>
```
